/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ui.restaurant.CreateRes;
import db04.DB4OUtil;
import ui.admin.AdminJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Systems;
import model.customer.Customer;
import model.deliveryman.Deliveryman;
import model.manager.Manager;
import ui.customer.CustomerPane;
import ui.deliveryman.DeliverymanPane;
import ui.manager.ManagerPane;

/**
 *
 * @author Siyuan He
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private String name = null;
    private Systems sys;

    public MainJFrame() {
        initComponents();
        sys = dB4OUtil.retrieveSystem();
        showRoles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        viewPane = new javax.swing.JPanel();
        btnlogin = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        pwdfield = new javax.swing.JPasswordField();
        cmbCity = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        creatPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnlogin.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        btnlogout.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        cmbCity.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cmbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin" }));
        cmbCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCityItemStateChanged(evt);
            }
        });
        cmbCity.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                cmbCityAncestorRemoved(evt);
            }
        });
        cmbCity.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                cmbCityComponentResized(evt);
            }
        });
        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jButton1.setText("Create Restaurants");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewPaneLayout = new javax.swing.GroupLayout(viewPane);
        viewPane.setLayout(viewPaneLayout);
        viewPaneLayout.setHorizontalGroup(
            viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdfield, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        viewPaneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnlogin, btnlogout, cmbCity, jButton1, pwdfield, txtusername});

        viewPaneLayout.setVerticalGroup(
            viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        viewPaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnlogin, btnlogout, cmbCity, jButton1, pwdfield, txtusername});

        splitPane.setLeftComponent(viewPane);

        javax.swing.GroupLayout creatPaneLayout = new javax.swing.GroupLayout(creatPane);
        creatPane.setLayout(creatPaneLayout);
        creatPaneLayout.setHorizontalGroup(
            creatPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        creatPaneLayout.setVerticalGroup(
            creatPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(creatPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:

        String userName = txtusername.getText();
        char[] passwordCharArray = pwdfield.getPassword();
        String password = String.valueOf(passwordCharArray);
        boolean flag = false;

        name = (String) cmbCity.getSelectedItem();

        if (userName.equals(sys.getAdmin().getUsername()) && password.equals(sys.getAdmin().getPassword())) {
            AdminJPanel adminJPanel = new AdminJPanel(sys);
            splitPane.setRightComponent(adminJPanel);
            flag = true;
            txtusername.setText("");
            pwdfield.setText("");
        } else {
            if (name.equals("Manager")) {
                Manager manager = null;

                for (Manager m : sys.getManagersDirectory().getManagersList()) {
                    if (m.getUsername().equals(userName) && m.getPassword().equals(password)) {
                        manager = m;
                        ManagerPane managerPane = new ManagerPane(sys, manager);
                        splitPane.setRightComponent(managerPane);
                        flag = true;
                        break;
                    }
                }

                if (flag == false) {
                    JOptionPane.showMessageDialog(this, "Invalid User Name/ Password.");
                    txtusername.setText("");
                    pwdfield.setText("");
                    return;
                } else {
                    txtusername.setText("");
                    pwdfield.setText("");
                    return;
                }
            } else if (name.equals("Customer")) {
                Customer customer = null;

                for (Customer m : sys.getCustomerDirectory().getCustomerList()) {
                    if (m.getUsername().equals(userName) && m.getPassword().equals(password)) {
                        customer = m;
                        CustomerPane customerPane = new CustomerPane(sys, customer);
                        splitPane.setRightComponent(customerPane);
                        flag = true;
                        break;
                    }
                }

                if (flag == false) {
                    JOptionPane.showMessageDialog(this, "Invalid User Name/ Password.");
                    txtusername.setText("");
                    pwdfield.setText("");
                    return;
                } else {
                    txtusername.setText("");
                    pwdfield.setText("");
                    return;
                }
            } else if (name.equals("Deliveryman")) {
                Deliveryman deliveryman = null;

                for (Deliveryman m : sys.getDeliverymanDirectory().getDeliverymanList()) {
                    if (m.getUsername().equals(userName) && m.getPassword().equals(password)) {
                        deliveryman = m;
                        DeliverymanPane deliverymanPane = new DeliverymanPane(sys, deliveryman);
                        splitPane.setRightComponent(deliverymanPane);
                        flag = true;
                        break;
                    }
                }

                if (flag == false) {
                    JOptionPane.showMessageDialog(this, "Invalid User Name/ Password.");
                    txtusername.setText("");
                    pwdfield.setText("");
                    return;
                } else {
                    txtusername.setText("");
                    pwdfield.setText("");
                    return;
                }
            }
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(this, "Invalid User Name/ Password.");
            txtusername.setText("");
            pwdfield.setText("");
            return;
        } else {
            txtusername.setText("");
            pwdfield.setText("");
            return;
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        LogoutPane logoutPane = new LogoutPane(sys, dB4OUtil);
        splitPane.setRightComponent(logoutPane);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void cmbCityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCityItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCityItemStateChanged

    private void cmbCityAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbCityAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCityAncestorRemoved

    private void cmbCityComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbCityComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCityComponentResized

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreateRes createRes = new CreateRes(sys);
        splitPane.setRightComponent(createRes);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JComboBox<String> cmbCity;
    private javax.swing.JPanel creatPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField pwdfield;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField txtusername;
    private javax.swing.JPanel viewPane;
    // End of variables declaration//GEN-END:variables

    private void showRoles() {
        cmbCity.addItem("Manager");
        cmbCity.addItem("Customer");
        cmbCity.addItem("Deliveryman");
    }
}
