/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.customer;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Systems;
import model.customer.Customer;
import model.manager.Manager;
import model.orders.Order;
import model.restaurants.Restaurant;

/**
 *
 * @author Siyuan He
 */
public class CustomerPane extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPane
     */
    private Systems sys;
    private Customer customer;
    private String name = null;
    private Restaurant restaurant;
    private Order order;

    public CustomerPane(Systems sys, Customer customer) {
        initComponents();
        this.sys = sys;
        this.customer = customer;
        showRes();
        populateOrders();
        lblRes.setText("Dashboard of Customer-- " + customer.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCity = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        txtOrder = new javax.swing.JTextField();
        btnOrder = new javax.swing.JButton();
        txtcom = new javax.swing.JTextField();
        btncom = new javax.swing.JButton();
        lblRes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnId = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblshow = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 210, 210));

        cmbCity.setBackground(new java.awt.Color(47, 64, 86));
        cmbCity.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cmbCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCityItemStateChanged(evt);
            }
        });
        cmbCity.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                cmbCityAncestorRemoved(evt);
            }
        });
        cmbCity.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                cmbCityComponentResized(evt);
            }
        });
        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(47, 64, 86));
        btnLogin.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        btnLogin.setText("OK");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        tblMenu.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Dish"
            }
        ));
        jScrollPane1.setViewportView(tblMenu);

        btnOrder.setBackground(new java.awt.Color(47, 64, 86));
        btnOrder.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        btnOrder.setText("OK");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btncom.setBackground(new java.awt.Color(47, 64, 86));
        btncom.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        btncom.setText("OK");
        btncom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomActionPerformed(evt);
            }
        });

        lblRes.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        lblRes.setText("jLabel1");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel3.setText("Select Menu:");

        btnId.setBackground(new java.awt.Color(47, 64, 86));
        btnId.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        btnId.setText("OK");
        btnId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdActionPerformed(evt);
            }
        });

        tblshow.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        tblshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Dish", "Status", "Restaurant", "Deliveryman", "Deliverd", "Comment"
            }
        ));
        jScrollPane3.setViewportView(tblshow);

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel4.setText("Select Dish:");

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel5.setText("Select order you want to comment by Id:");

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel6.setText("Input the comment:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcom))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnId)
                                    .addComponent(btncom))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnId)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncom)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogin)
                            .addComponent(btnOrder)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnId, btnOrder, jLabel3, jLabel4, jLabel5, txtId, txtOrder});

    }// </editor-fold>//GEN-END:initComponents

    private void cmbCityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCityItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCityItemStateChanged

    private void cmbCityAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbCityAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCityAncestorRemoved

    private void cmbCityComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbCityComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCityComponentResized

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbCityActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        name = (String) cmbCity.getSelectedItem();

        for (Restaurant r : sys.getRestaurantDirectory().getRestaurantList()) {
            if (name.equals(r.getName())) {
                restaurant = r;
                popluateMenu();
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        Restaurant temp = null;

        for (Restaurant m : sys.getRestaurantDirectory().getRestaurantList()) {
            if (m.getName().equals(name)) {
                temp = m;
            }
        }

        boolean flag = false;

        for (String s : temp.getMenu()) {
            if (s.equalsIgnoreCase(txtOrder.getText())) {
                flag = true;
            }
        }

        if (!flag) {
            JOptionPane.showMessageDialog(this, "Please input correct Dish!", "Warning", JOptionPane.ERROR_MESSAGE);
            txtOrder.setText("");
            return;
        }

        customer.getOrders().add(new Order(txtOrder.getText(), temp, customer.getName()));

        populateOrders();
        txtOrder.setText("");
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btncomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomActionPerformed
        // TODO add your handling code here:
        if (txtcom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input comment!", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (order == null) {
            JOptionPane.showMessageDialog(this, "Please input Id!", "Warning", JOptionPane.ERROR_MESSAGE);
            txtcom.setText("");
            return;
        }

        order.setComment(txtcom.getText());
        txtcom.setText("");
        txtId.setText("");
        populateOrders();
    }//GEN-LAST:event_btncomActionPerformed

    private void btnIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdActionPerformed
        // TODO add your handling code here:
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input correct Id!", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!txtId.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Please input correct Id!", "Warning", JOptionPane.ERROR_MESSAGE);
            txtId.setText("");
            return;
        }

        int id = Integer.parseInt(txtId.getText());

        for (Order s : customer.getOrders()) {
            if (id == s.getId()) {
                order = s;
                break;
            }
        }

        if (order == null) {
            JOptionPane.showMessageDialog(this, "Order not Found!", "Warning", JOptionPane.ERROR_MESSAGE);
            txtId.setText("");
            return;
        }

        if (!order.isMark()) {
            JOptionPane.showMessageDialog(this, "Order is not delivered!", "Warning", JOptionPane.ERROR_MESSAGE);
            txtId.setText("");
            return;
        }

        JOptionPane.showMessageDialog(this, "Please leave a comment!");
    }//GEN-LAST:event_btnIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnId;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btncom;
    private javax.swing.JComboBox<String> cmbCity;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblRes;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblshow;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtOrder;
    private javax.swing.JTextField txtcom;
    // End of variables declaration//GEN-END:variables

    private void showRes() {
        for (Restaurant r : sys.getRestaurantDirectory().getRestaurantList()) {
            cmbCity.addItem(r.getName());
        }
    }

    private void populateOrders() {
        DefaultTableModel model = (DefaultTableModel) tblshow.getModel();
        model.setRowCount(0);
        for (Order o : customer.getOrders()) {
            Object[] row = new Object[7];
            row[0] = o.getId();
            row[1] = o.getDish();
            if (o.isStatus()) {
                row[2] = "Accepted";
            } else {
                row[2] = "Not accepted";
            }
            row[3] = o.getRestaurant().getName();
            if (o.getDeliveryman() != null) {
                row[4] = o.getDeliveryman().getName();
            }
            if (o.isMark() == true) {
                row[5] = "Delivered";
            } else {
                row[5] = "Not Delivered";
            }
            if (o.getComment() != null) {
                row[6] = o.getComment();
            }
            model.addRow(row);
        }
    }

    private void popluateMenu() {
        DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
        model.setRowCount(0);
        for (String s : restaurant.getMenu()) {
            Object[] row = new Object[1];
            row[0] = s;
            model.addRow(row);
        }
    }
}
